apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: pod-labeler
webhooks:
  - name: pod-labeler.default.svc.cluster.local
    admissionReviewVersions:
      - "v1beta1"
    sideEffects: "None"
    timeoutSeconds: 30
    namespaceSelector:
      matchExpressions:
      - key: pod-labeler
        operator: In
        values:
        - enabled
    objectSelector: {}
    clientConfig:
      service:
        name: pod-labeler
        namespace: default
        path: /mutate
      caBundle: CA_PEM_B64
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["apps", ""]
        apiVersions: ["*"]
        resources: ["deployments", "pods"]