apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "pod-labeler.fullname" . }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "pod-labeler.fullname" . }}
  annotations:
    cert-manager.io/allow-direct-injection: "true"
spec:
  dnsNames:
  - {{ include "pod-labeler.fullname" . }}.{{ .Release.Namespace }}.svc
  - {{ include "pod-labeler.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ include "pod-labeler.fullname" . }}
  secretName: {{ include "pod-labeler.fullname" . }}