apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "pod-labeler.fullname" . }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "pod-labeler.fullname" . }} # This is the cert-manager certificate name
webhooks:
  - name: {{ include "pod-labeler.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
    admissionReviewVersions:
      - "v1beta1"
    sideEffects: "None"
    timeoutSeconds: 30
    namespaceSelector:
      matchExpressions:
      - key: pod-labeler
        operator: In
        values:
        - enabled
    objectSelector: {}
    clientConfig:
      service:
        name: {{ include "pod-labeler.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: /mutate
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["apps", ""]
        apiVersions: ["*"]
        resources: ["deployments", "pods"]