name: docker

on:
  push:
    tags:
      - '*'
    branches:
      - 'main'
    paths:
      - '!infra/pod-labeler/**'
      - '!README.md'
  pull_request:
    branches: [ 'main' ]
    paths:
      - '!infra/pod-labeler/**'
      - '!README.md'
      - '.github/workflows/docker.yaml'
      
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: infra/Dockerfile
          push: true
          tags: ${{ github.repository }}:${{ github.sha }}-${{ github.run_number }}
